src/java/controlador/UsuarioController.java
package controlador;

import clarkewright.ClarkeWright;
import clarkewright.Cliente;
import clarkewright.Colonia;
import clarkewright.Entrega;
import clarkewright.Nodo;
import clarkewright.Ruta;
import entidad.Usuario;
import controlador.util.JsfUtil;
import controlador.util.PaginationHelper;
import entidad.Bodega;
import entidad.Lista;
import java.io.File;
import java.io.IOException;
import session.UsuarioFacade;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.List;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem; 
import javax.servlet.ServletOutputStream;
import javax.servlet.http.HttpServletResponse;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import javax.faces.context.FacesContext;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;

@ManagedBean(name = "usuarioController")
@SessionScoped
public class UsuarioController implements Serializable {

    private Usuario current;
    private DataModel items = null;
    @EJB
    private session.UsuarioFacade ejbFacade;
    @EJB    
    private session.ClienteFacade ejbFacadeCli;
    @EJB
    private session.ColoniasFacade ejbFacadeCol;
    @EJB
    private session.BodegaFacade ejbFacadeBod;
    @EJB
    private session.EntragaFacade ejbFacadeEnt;
    private PaginationHelper pagination;
    private int selectedItemIndex;
    @Size(min=3, message="Debe ser minimo 3 caracteres")
    @Pattern(regexp="^[a-zA-Z0-9]*$" , message="Solo numeros y letras ")
    private String login;
    @Size(min=3, message="Debe ser minimo 3 caracteres")
    private String pwd;
    private List<Lista> lista;
    private List<Entrega> relacion_ent;
    
    JasperPrint jasperPrint;

    public List<Entrega> getRelacion_entrega() {
        return relacion_ent;
    }

    public void setRelacion_entrega(List<Entrega> relacion_entrega) {
        this.relacion_ent = relacion_entrega;
    }
    
    
    public void init() throws JRException
    {
        Collection <Lista> o=(Collection <Lista> )lista;
        JRBeanCollectionDataSource beanCollectionDataSource=new JRBeanCollectionDataSource(o);
        String ruta="C:\\Users\\Faby\\Desktop\\NUEVO\\trescinco\\src\\java\\report\\reporte.jasper";
        String reportPath1=FacesContext.getCurrentInstance().getExternalContext().getRealPath("/report/reporte.jasper");
        jasperPrint=JasperFillManager.fillReport(ruta, new HashMap(), beanCollectionDataSource);
    }
    
    public void PDF() throws JRException, IOException
    {
        init();
        HttpServletResponse httpServletResponse=(HttpServletResponse)FacesContext.getCurrentInstance().getExternalContext().getResponse();
        httpServletResponse.addHeader("Content-disposition", "attachment;filename=report.pdf");
        ServletOutputStream servletOutputStream=httpServletResponse.getOutputStream();
        JasperExportManager.exportReportToPdfStream(jasperPrint, servletOutputStream);
        FacesContext.getCurrentInstance().responseComplete();
    }
    public List<Lista> getLista() {
        lista=this.getFacade().PorEntregar(current.getBodega().getId(),"06/4/2015") ;
        
        return lista;
    }

    public void setLista(List<Lista> lista) {
        this.lista = lista;
    }
    
    public String acceso() {
        try {
            Usuario usu=getFacade().findUser(getLogin(),getPwd());
            current=usu;
            System.out.println("*********************************");
            System.out.println(usu.toString());
            System.out.println(getLogin());
            System.out.println(getPwd());
            return "principal";
        }catch(Exception e){
            System.out.println("Error no se equivoco en el usuario o contraseña");
            return "index";
        }
           
    }
    
    public String ruta() {
        
        Bodega bodega=ejbFacadeBod.findById(current.getBodega().getId());
        double bodegaLat=bodega.getLatitud();
        double bodegaLon=bodega.getLongitud();
       
        ArrayList<Nodo> entregas=new ArrayList<>();
       
        //Todoas las colonias que se entregen al dia siguiente (unique)
        //Lista de id_colonia, latitud, longitud                
        List<Colonia> colonias=ejbFacadeCol.getColonias(current.getBodega().getId(), "06/4/2015");
       
       
        for (int i = 0; i < colonias.size(); i++)        
        {            
            double peso=0;
            double tiempo=0;
            //Todos los clientes de la colonia que se entregen al dia sih¿guiente
            //Lista de clientes (peso, cantidad) donde id_colonia=colonias.get(i).getIDColonia()
            List<Cliente> clientes=ejbFacadeCli.getClientes(current.getBodega().getId(), "06/4/2015", colonias.get(i).getId());
            for (int j = 0; j < clientes.size(); j++)
            {
                peso=peso+clientes.get(j).getPeso();
                if(clientes.get(j).getCantidad()>1)
                    tiempo=tiempo+0.41;
                else
                    tiempo=tiempo+0.33;
            }                        
            entregas.add(new Nodo(i + 1,colonias.get(i).getLatitud(),colonias.get(i).getLongitud(),peso, tiempo, colonias.get(i).getId()));
       
        }        
       
        ClarkeWright clarkewright=new ClarkeWright();
        ArrayList<Ruta> rutas=clarkewright.clarkeWright(entregas, bodegaLat, bodegaLon);
        List<Entrega> relacion_entregas=ejbFacadeEnt.getEntregas(current.getBodega().getId(), "06/4/2015");
        
        for (Ruta ruta : rutas)
        {   
            if(ruta.getNodos().size() > 0)
            {
                int id_camion=ruta.getId();                            

                for (Nodo nodo : ruta.getNodos())
                {                    
                    for (Entrega relacion_entrega : relacion_entregas)
                    {
                        if(nodo.getColonia() == relacion_entrega.getId_colonia())
                        {
                            relacion_entrega.setId_camion(id_camion);
                            relacion_entrega.setH_entrega(nodo.getTime());
                        }
                    }
                }                        
            }
        }
        relacion_ent=relacion_entregas;
        return "ruta";
    }
   
    public String getLogin() {
        return login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public String getPwd() {
        return pwd;
    }

    public void setPwd(String pwd) {
        this.pwd = pwd;
    }
    
    public UsuarioController() {
    }

    public Usuario getSelected() {
        if (current == null) {
            current = new Usuario();
            selectedItemIndex = -1;
        }
        return current;
    }

    private UsuarioFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Usuario) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Usuario();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("UsuarioCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Usuario) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("UsuarioUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Usuario) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {

src/java/controlador/VentaController.java
package controlador;

import entidad.Venta;
import controlador.util.JsfUtil;
import controlador.util.PaginationHelper;
import session.VentaFacade;

import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@ManagedBean(name = "ventaController")
@SessionScoped
public class VentaController implements Serializable {

    private Venta current;
    private DataModel items = null;
    @EJB
    private session.VentaFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public VentaController() {
    }

    public Venta getSelected() {
        if (current == null) {
            current = new Venta();
            selectedItemIndex = -1;
        }
        return current;
    }

    private VentaFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Venta) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Venta();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("VentaCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Venta) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("VentaUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Venta) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("VentaDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    @FacesConverter(forClass = Venta.class)
    public static class VentaControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            VentaController controller = (VentaController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "ventaController");
            return controller.ejbFacade.find(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Venta) {
                Venta o = (Venta) object;
                return getStringKey(o.getId());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Venta.class.getName());
            }
        }

    }

}

web/entidad/usuario/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreateUsuarioTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreateUsuarioLabel_id}" for="id" />
                    <h:inputText id="id" value="#{usuarioController.selected.id}" title="#{bundle.CreateUsuarioTitle_id}" required="true" requiredMessage="#{bundle.CreateUsuarioRequiredMessage_id}"/>
                    <h:outputLabel value="#{bundle.CreateUsuarioLabel_login}" for="login" />
                    <h:inputTextarea rows="4" cols="30" id="login" value="#{usuarioController.selected.login}" title="#{bundle.CreateUsuarioTitle_login}" required="true" requiredMessage="#{bundle.CreateUsuarioRequiredMessage_login}"/>
                    <h:outputLabel value="#{bundle.CreateUsuarioLabel_pwd}" for="pwd" />
                    <h:inputTextarea rows="4" cols="30" id="pwd" value="#{usuarioController.selected.pwd}" title="#{bundle.CreateUsuarioTitle_pwd}" required="true" requiredMessage="#{bundle.CreateUsuarioRequiredMessage_pwd}"/>
                    <h:outputLabel value="#{bundle.CreateUsuarioLabel_nombre}" for="nombre" />
                    <h:inputTextarea rows="4" cols="30" id="nombre" value="#{usuarioController.selected.nombre}" title="#{bundle.CreateUsuarioTitle_nombre}" required="true" requiredMessage="#{bundle.CreateUsuarioRequiredMessage_nombre}"/>
                    <h:outputLabel value="#{bundle.CreateUsuarioLabel_privilegio}" for="privilegio" />
                    <h:inputTextarea rows="4" cols="30" id="privilegio" value="#{usuarioController.selected.privilegio}" title="#{bundle.CreateUsuarioTitle_privilegio}" required="true" requiredMessage="#{bundle.CreateUsuarioRequiredMessage_privilegio}"/>
                    <h:outputLabel value="#{bundle.CreateUsuarioLabel_bodega}" for="bodega" />
                    <h:selectOneMenu id="bodega" value="#{usuarioController.selected.bodega}" title="#{bundle.CreateUsuarioTitle_bodega}" required="true" requiredMessage="#{bundle.CreateUsuarioRequiredMessage_bodega}">
                        <f:selectItems value="#{bodegaController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{usuarioController.create}" value="#{bundle.CreateUsuarioSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{usuarioController.prepareList}" value="#{bundle.CreateUsuarioShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.CreateUsuarioIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/entidad/usuario/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditUsuarioTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditUsuarioLabel_id}" for="id" />
                    <h:inputText id="id" value="#{usuarioController.selected.id}" title="#{bundle.EditUsuarioTitle_id}" required="true" requiredMessage="#{bundle.EditUsuarioRequiredMessage_id}"/>
                    <h:outputLabel value="#{bundle.EditUsuarioLabel_login}" for="login" />
                    <h:inputTextarea rows="4" cols="30" id="login" value="#{usuarioController.selected.login}" title="#{bundle.EditUsuarioTitle_login}" required="true" requiredMessage="#{bundle.EditUsuarioRequiredMessage_login}"/>
                    <h:outputLabel value="#{bundle.EditUsuarioLabel_pwd}" for="pwd" />
                    <h:inputTextarea rows="4" cols="30" id="pwd" value="#{usuarioController.selected.pwd}" title="#{bundle.EditUsuarioTitle_pwd}" required="true" requiredMessage="#{bundle.EditUsuarioRequiredMessage_pwd}"/>
                    <h:outputLabel value="#{bundle.EditUsuarioLabel_nombre}" for="nombre" />
                    <h:inputTextarea rows="4" cols="30" id="nombre" value="#{usuarioController.selected.nombre}" title="#{bundle.EditUsuarioTitle_nombre}" required="true" requiredMessage="#{bundle.EditUsuarioRequiredMessage_nombre}"/>
                    <h:outputLabel value="#{bundle.EditUsuarioLabel_privilegio}" for="privilegio" />
                    <h:inputTextarea rows="4" cols="30" id="privilegio" value="#{usuarioController.selected.privilegio}" title="#{bundle.EditUsuarioTitle_privilegio}" required="true" requiredMessage="#{bundle.EditUsuarioRequiredMessage_privilegio}"/>
                    <h:outputLabel value="#{bundle.EditUsuarioLabel_bodega}" for="bodega" />
                    <h:selectOneMenu id="bodega" value="#{usuarioController.selected.bodega}" title="#{bundle.EditUsuarioTitle_bodega}" required="true" requiredMessage="#{bundle.EditUsuarioRequiredMessage_bodega}">
                        <f:selectItems value="#{bodegaController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <h:commandLink action="#{usuarioController.update}" value="#{bundle.EditUsuarioSaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{bundle.EditUsuarioViewLink}"/>
                <br />
                <h:commandLink action="#{usuarioController.prepareList}" value="#{bundle.EditUsuarioShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.EditUsuarioIndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/entidad/usuario/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListUsuarioTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle.ListUsuarioEmpty}" rendered="#{usuarioController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{usuarioController.items.rowCount > 0}">
                    <h:outputText value="#{usuarioController.pagination.pageFirstItem + 1}..#{usuarioController.pagination.pageLastItem + 1}/#{usuarioController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{usuarioController.previous}" value="#{bundle.Previous} #{usuarioController.pagination.pageSize}" rendered="#{usuarioController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{usuarioController.next}" value="#{bundle.Next} #{usuarioController.pagination.pageSize}" rendered="#{usuarioController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{usuarioController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListUsuarioTitle_id}"/>
                            </f:facet>
                            <h:outputText value="#{item.id}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListUsuarioTitle_login}"/>
                            </f:facet>
                            <h:outputText value="#{item.login}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListUsuarioTitle_pwd}"/>
                            </f:facet>
                            <h:outputText value="#{item.pwd}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListUsuarioTitle_nombre}"/>
                            </f:facet>
                            <h:outputText value="#{item.nombre}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListUsuarioTitle_privilegio}"/>
                            </f:facet>
                            <h:outputText value="#{item.privilegio}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListUsuarioTitle_bodega}"/>
                            </f:facet>
                            <h:outputText value="#{item.bodega}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{usuarioController.prepareView}" value="#{bundle.ListUsuarioViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{usuarioController.prepareEdit}" value="#{bundle.ListUsuarioEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{usuarioController.destroy}" value="#{bundle.ListUsuarioDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{usuarioController.prepareCreate}" value="#{bundle.ListUsuarioCreateLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ListUsuarioIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>