src/java/controlador/UsuarioController.java
package controlador;

import clarkewright.ClarkeWright;
import clarkewright.Cliente;
import clarkewright.Colonia;
import clarkewright.Entrega;
import clarkewright.Nodo;
import clarkewright.Ruta;
import entidad.Usuario;
import controlador.util.JsfUtil;
import controlador.util.PaginationHelper;
import entidad.Bodega;
import entidad.Lista;
import java.io.File;
import java.io.IOException;
import session.UsuarioFacade;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.List;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem; 
import javax.servlet.ServletOutputStream;
import javax.servlet.http.HttpServletResponse;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import javax.faces.context.FacesContext;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;

@ManagedBean(name = "usuarioController")
@SessionScoped
public class UsuarioController implements Serializable {

    private Usuario current;
    private DataModel items = null;
    @EJB
    private session.UsuarioFacade ejbFacade;
    @EJB    
    private session.ClienteFacade ejbFacadeCli;
    @EJB
    private session.ColoniasFacade ejbFacadeCol;
    @EJB
    private session.BodegaFacade ejbFacadeBod;
    @EJB
    private session.EntragaFacade ejbFacadeEnt;
    private PaginationHelper pagination;
    private int selectedItemIndex;
    @Size(min=3, message="Debe ser minimo 3 caracteres")
    @Pattern(regexp="^[a-zA-Z0-9]*$" , message="Solo numeros y letras ")
    private String login;
    @Size(min=3, message="Debe ser minimo 3 caracteres")
    private String pwd;
    private List<Lista> lista;
    private List<Entrega> relacion_ent;
    
    JasperPrint jasperPrint;

    public List<Entrega> getRelacion_entrega() {
        return relacion_ent;
    }

    public void setRelacion_entrega(List<Entrega> relacion_entrega) {
        this.relacion_ent = relacion_entrega;
    }
    
    
    public void init() throws JRException
    {
        Collection <Lista> o=(Collection <Lista> )lista;
        JRBeanCollectionDataSource beanCollectionDataSource=new JRBeanCollectionDataSource(o);
        String ruta="C:\\Users\\Faby\\Desktop\\NUEVO\\trescinco\\src\\java\\report\\reporte.jasper";
        String reportPath1=FacesContext.getCurrentInstance().getExternalContext().getRealPath("/report/reporte.jasper");
        jasperPrint=JasperFillManager.fillReport(ruta, new HashMap(), beanCollectionDataSource);
    }
    
    public void PDF() throws JRException, IOException
    {
        init();
        HttpServletResponse httpServletResponse=(HttpServletResponse)FacesContext.getCurrentInstance().getExternalContext().getResponse();
        httpServletResponse.addHeader("Content-disposition", "attachment;filename=report.pdf");
        ServletOutputStream servletOutputStream=httpServletResponse.getOutputStream();
        JasperExportManager.exportReportToPdfStream(jasperPrint, servletOutputStream);
        FacesContext.getCurrentInstance().responseComplete();
    }
    public List<Lista> getLista() {
        lista=this.getFacade().PorEntregar(current.getBodega().getId(),"06/4/2015") ;
        
        return lista;
    }

    public void setLista(List<Lista> lista) {
        this.lista = lista;
    }
    
    public String acceso() {
        try {
            Usuario usu=getFacade().findUser(getLogin(),getPwd());
            current=usu;
            System.out.println("*********************************");
            System.out.println(usu.toString());
            System.out.println(getLogin());
            System.out.println(getPwd());
            return "principal";
        }catch(Exception e){
            System.out.println("Error no se equivoco en el usuario o contraseña");
            return "index";
        }
           
    }
    
    public String ruta() {
        
        Bodega bodega=ejbFacadeBod.findById(current.getBodega().getId());
        double bodegaLat=bodega.getLatitud();
        double bodegaLon=bodega.getLongitud();
       
        ArrayList<Nodo> entregas=new ArrayList<>();
       
        //Todoas las colonias que se entregen al dia siguiente (unique)
        //Lista de id_colonia, latitud, longitud                
        List<Colonia> colonias=ejbFacadeCol.getColonias(current.getBodega().getId(), "06/4/2015");
       
       
        for (int i = 0; i < colonias.size(); i++)        
        {            
            double peso=0;
            double tiempo=0;
            //Todos los clientes de la colonia que se entregen al dia sih¿guiente
            //Lista de clientes (peso, cantidad) donde id_colonia=colonias.get(i).getIDColonia()
            List<Cliente> clientes=ejbFacadeCli.getClientes(current.getBodega().getId(), "06/4/2015", colonias.get(i).getId());
            for (int j = 0; j < clientes.size(); j++)
            {
                peso=peso+clientes.get(j).getPeso();
                if(clientes.get(j).getCantidad()>1)
                    tiempo=tiempo+0.41;
                else
                    tiempo=tiempo+0.33;
            }                        
            entregas.add(new Nodo(i + 1,colonias.get(i).getLatitud(),colonias.get(i).getLongitud(),peso, tiempo, colonias.get(i).getId()));
       
        }        
       
        ClarkeWright clarkewright=new ClarkeWright();
        ArrayList<Ruta> rutas=clarkewright.clarkeWright(entregas, bodegaLat, bodegaLon);
        List<Entrega> relacion_entregas=ejbFacadeEnt.getEntregas(current.getBodega().getId(), "06/4/2015");
        
        for (Ruta ruta : rutas)
        {   
            if(ruta.getNodos().size() > 0)
            {
                int id_camion=ruta.getId();                            

                for (Nodo nodo : ruta.getNodos())
                {                    
                    for (Entrega relacion_entrega : relacion_entregas)
                    {
                        if(nodo.getColonia() == relacion_entrega.getId_colonia())
                        {
                            relacion_entrega.setId_camion(id_camion);
                            relacion_entrega.setH_entrega(nodo.getTime());
                        }
                    }
                }                        
            }
        }
        relacion_ent=relacion_entregas;
        return "ruta";
    }
   
    public String getLogin() {
        return login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public String getPwd() {
        return pwd;
    }

    public void setPwd(String pwd) {
        this.pwd = pwd;
    }
    
    public UsuarioController() {
    }

    public Usuario getSelected() {
        if (current == null) {
            current = new Usuario();
            selectedItemIndex = -1;
        }
        return current;
    }

    private UsuarioFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Usuario) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Usuario();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("UsuarioCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Usuario) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("UsuarioUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Usuario) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {

web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>LOGIN</title>
        <h:outputStylesheet name="css/styles.css"/>
    </h:head>
    <h:body >
        <div align="center">
            <table>
                <tr>
                    <td>
                        <h:graphicImage library="img" name="afirmacje-lock.png"/>
                    </td>
                    <td>
                        <h:form class="contact_form">
                            <h2>LOGIN</h2>
                            <h:panelGrid columns="3"  >         
                                <h:outputLabel for="username">Username:</h:outputLabel> 

                                <h:inputText id="username" value="#{usuarioController.login}" required="true" requiredMessage="Ingresa tu usuario"/> 

                                <h:message for="username" style="color: red;" />

                                <h:outputLabel for="password">Password:</h:outputLabel> 

                                <h:inputSecret id="password" value="#{usuarioController.pwd}" required="true"  requiredMessage="Ingresa tu contraseña"/> 

                                <h:message for="password" style="color: red;" />
                            </h:panelGrid> 
                            <h:commandButton id="login" class="submit" value="Entrar" action="#{usuarioController.acceso()}" /> 
                        </h:form>

                    </td>
                </tr>
            </table>
        </div>
    </h:body>

</html>

web/principal.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Entregas</title>
        <h:outputStylesheet name="css/styles.css"/>
    </h:head>
    <h:body>

        <div align="center">
            <h1>BIENVENIDO</h1></div>
            <div align="LEFT">Login: #{usuarioController.selected.login}</div>       
            <div align="RIGHT">Bodega: #{usuarioController.selected.bodega.nombre} /#{usuarioController.selected.bodega.id}</div>
        <h:form>
            <table>
  
            <tr>
                <td><h:form>
                        <p:commandButton id="login" class="submit" value="Calcular" action="#{usuarioController.ruta()}" /> 
                    </h:form>
                </td>
                <td><h:commandLink  action="#{usuarioController.PDF()}">
                        <h:graphicImage name="pdf.png" library="img" />
                    </h:commandLink> 
                </td> 
            </tr>
            </table>
            <BR/>
            <p:dataTable value="#{usuarioController.lista}" var="item" styleClass="table" paginator="true" >
                <p:column>
                    <f:facet name="header">
                        <h:outputText value="BODEGA"/>
                    </f:facet>
                    <h:outputText value="#{item.idBodega}"/>
                </p:column>
                <p:column>
                    <f:facet name="header">
                        <h:outputText value="ESTADO"/>
                    </f:facet>
                    <h:outputText value="#{item.estado}"/>
                </p:column>
                <p:column>
                    <f:facet name="header">
                        <h:outputText value="MUNICIPIO"/>
                    </f:facet>
                    <h:outputText value="#{item.municipio}"/>
                </p:column>
                <p:column>
                    <f:facet name="header">
                        <h:outputText value="LOCALIDAD"/>
                    </f:facet>
                    <h:outputText value="#{item.localidad}"/>
                </p:column>
                <p:column>
                    <f:facet name="header">
                        <h:outputText value="VENTA"/>
                    </f:facet>
                    <h:outputText value="#{item.idVenta}"/>
                </p:column>
                <p:column>
                    <f:facet name="header">
                        <h:outputText value="ID MAQUINARIA"/>
                    </f:facet>
                    <h:outputText value="#{item.idMaq}"/>
                </p:column>
                <p:column>
                    <f:facet name="header">
                        <h:outputText value="MAQUINARIA"/>
                    </f:facet>
                    <h:outputText value="#{item.nomMaq}"/>
                </p:column>
                <p:column>
                    <f:facet name="header">
                        <h:outputText value="CANTIDAD"/>
                    </f:facet>
                    <h:outputText value="#{item.cantidad}"/>
                </p:column>
                <p:column>
                    <f:facet name="header">
                        <h:outputText value="PESO"/>
                    </f:facet>
                    <h:outputText value="#{item.peso}"/>
                </p:column>
                <p:column>
                    <f:facet name="header">
                        <h:outputText value="PESO TOTAL"/>
                    </f:facet>
                    <h:outputText value="#{item.totalPeso}"/>
                </p:column>
            </p:dataTable>
            
        </h:form>
        
        






    </h:body>
</html>

web/ruta.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Rutas</title>
        <h:outputStylesheet name="css/styles.css"/>
    </h:head>
    <h:body>
        <h:form>
        <div align="center">
            <h1>RUTAS PARA MAÑANA</h1></div>
   
            <BR/>
            <p:dataTable value="#{usuarioController.relacion_entrega}" var="item" styleClass="table" paginator="true" >
                <p:column>
                    <f:facet name="header">
                        <h:outputText value="CAMION"/>
                    </f:facet>
                    <h:outputText value="#{item.id_camion}"/>
                </p:column>
                <p:column>
                    <f:facet name="header">
                        <h:outputText value="CALLE"/>
                    </f:facet>
                    <h:outputText value="#{item.calle}"/>
                </p:column>
                <p:column>
                    <f:facet name="header">
                        <h:outputText value="NUMERO"/>
                    </f:facet>
                    <h:outputText value="#{item.numero}"/>
                </p:column>
                <p:column>
                    <f:facet name="header">
                        <h:outputText value="COLONIA"/>
                    </f:facet>
                    <h:outputText value="#{item.colonia}"/>
                </p:column>
                <p:column>
                    <f:facet name="header">
                        <h:outputText value="MAQUINARIA"/>
                    </f:facet>
                    <h:outputText value="#{item.maquinaria}"/>
                </p:column>
                <p:column>
                    <f:facet name="header">
                        <h:outputText value="CANTIDAD"/>
                    </f:facet>
                    <h:outputText value="#{item.cantidad}"/>
                </p:column>
                <p:column>
                    <f:facet name="header">
                        <h:outputText value="PESO"/>
                    </f:facet>
                    <h:outputText value="#{item.peso}"/>
                </p:column>
                <p:column>
                    <f:facet name="header">
                        <h:outputText value="ENTREGA"/>
                    </f:facet>
                    <h:outputText value="#{item.h_entrega}"/>
                </p:column>
            </p:dataTable>
            
        </h:form>
    </h:body>
</html>

web/template.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html">

    <h:head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title><ui:insert name="title">Default Title</ui:insert></title>
        <h:outputStylesheet library="css" name="jsfcrud.css"/>
    </h:head>

    <h:body>
        <h1>
            <ui:insert name="title">Default Title</ui:insert>
        </h1>
        <p>
            <ui:insert name="body">Default Body</ui:insert>
        </p>
    </h:body>

</html>

web/welcomePrimefaces.xhtml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">

    <f:view contentType="text/html">
        <h:head>
            <f:facet name="first">
                <meta content='text/html; charset=UTF-8' http-equiv="Content-Type"/>
                <title>PrimeFaces</title>
            </f:facet>
        </h:head>

        <h:body>

            <p:layout fullPage="true">

                <p:layoutUnit position="north" size="100" resizable="true" closable="true" collapsible="true">
                    Header
                </p:layoutUnit>

                <p:layoutUnit position="south" size="100" closable="true" collapsible="true">
                    Footer
                </p:layoutUnit>

                <p:layoutUnit position="west" size="175" header="Left" collapsible="true">
                    <p:menu>
                        <p:submenu label="Resources">
                            <p:menuitem value="Demo" url="http://www.primefaces.org/showcase-labs/ui/home.jsf" />
                            <p:menuitem value="Documentation" url="http://www.primefaces.org/documentation.html" />
                            <p:menuitem value="Forum" url="http://forum.primefaces.org/" />
                            <p:menuitem value="Themes" url="http://www.primefaces.org/themes.html" />

                        </p:submenu>

                    </p:menu>
                </p:layoutUnit>

                <p:layoutUnit position="center">
                    Welcome to PrimeFaces
                </p:layoutUnit>

            </p:layout>

        </h:body>

    </f:view>
</html>